image:
  registry: docker.io
  repository: bitnami/jenkins
  tag: 2.332.3-debian-11-r3

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: jenkins.halocheck.xyz
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true
  #selfSigned: true